version: '3.9'
services:
  db:
    image: postgres:14
    container_name: ${APP_NAME}_db
    hostname: db
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - .env

  server:
    build:
      context: .
      args:
        - APP_NAME=${APP_NAME}
    container_name: ${APP_NAME}_server
    hostname: server
    ports:
      - 8000:${PORT:-8000}
    volumes:
      - .:/go/src/${APP_NAME}
    env_file:
      - .env
    depends_on:
      - db
      
  adminer:
    container_name: ${APP_NAME}_adminer
    image: adminer:4.7.5
    ports:
      - 8080:8080

volumes:
  dbdata:
    name: ${APP_NAME}_volume